CREATE TABLE `feed` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `id_owner` INTEGER NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `lastread` VARCHAR(120) NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE `user` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE `item_posted` (
  `id`INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `id_feed` INTEGER NOT NULL,
  `guid` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
);
